telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CD1E80>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE278>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE400>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE518>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE470>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE780>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE8D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE9E8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDE630>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDEC50>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDEDA0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot525299103:AAHfha3orrDK7khmGe6GKVKkyBkSAiqK0Zg/deleteWebhook (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000000003CDEEB8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.ext.updater - WARNING - Exiting immediately!
